### ISSUE TITLE
Enable translation

### ISSUE THREAD

**Issue by tobbexiv** [tobbexiv/pagekit-widget-includer#10]
Set up transifex etc.

**Comment by tobbexiv** [comment]
Now available on transifex: https://www.transifex.com/tobbe/pagekit-widget-includer/

**Comment by tobbexiv** [comment]
@jdegger I removed the languages which are not present in the pagekit core as you cannot choose them and thus translating makes no sense.

**Comment by jdegger** [comment]
@tobbexiv do you need `nl` or `nl_NL`?

**Comment by tobbexiv** [comment]
nl_NL is only available in pagekit. But it is possible to copy the translations if you say that they are both the same. Then you do not have to translate everything twice.

For the future I will check this beforehand :)

**Comment by jdegger** [comment]
Haha no worries, they are the same :)

**Comment by tobbexiv** [comment]
Ok. I copied it and deleted the main source. Thanks for translating :)

**Comment by jdegger** [comment]
Cheers! We still happily use this plugin on our website so thanks for the effort you put into this.
