### ISSUE TITLE
Fatal error (Call to undefined function _() )

### ISSUE THREAD

**Issue by ahoiroman** [tobbexiv/pagekit-widget-includer#11]
After installing your plugin I get the following error:

> Fatal error: Call to undefined function _() in /Users/rlb/Entwicklung/Pagekit/Pagekit-run/pagekit-1/packages/tobbe/widget-includer/index.php on line 17

which refers to

   ```
 'permissions' => [
        'widgetincluder: use editor plugin' => [
            'title' => _('Use the widget includer editor plugin')
        ]
    ],
```

Not sure if this problem appears on full webhosting-environments, I am facing this using the pagekit-server locally.

**Comment by tobbexiv** [comment]
Interesting issue. I never faced any problems with this. Neither locally nor on a server. But `_` (one underscore) is wrong and should be `__` (two underscores). For a quick fix you can edit it manually and then check whether it works.

**Comment by tobbexiv** [comment]
Seems that the first issue depends on the php version. In my system there was a php command `_` for translation which just got executed => no error.

`__` will also not work. Thus different approach.
