### ISSUE TITLE
"Insert Widget" menu item missing in TinyMCE

### ISSUE THREAD

**Issue by shchukax** [tobbexiv/pagekit-widget-includer#12]
I installed TinyMCE extension and the widget picker extension, however widgets are not appearing in the "insert" menu. If I disable TinyMCE and use the default editor, then I do have the widget picker icon in the toolbar, so, seemingly, only TinyMCE is affected.

**Comment by tobbexiv** [comment]
This is an interesting bug. It depends on the installation order. If you install the TinyMCE extension first and afterwards the widget includer, then it does not work. If you do the other way around, then it works. So as a workaround you can uninstall the TinyMCE extension and install it again. Then you changed the order in which the extensions are called and everything should work as expected. At least this did it for me.

I will keep this issue open as this should be fixed.
