### ISSUE TITLE
Decide on icon for editor button

### ISSUE THREAD

**Issue by tobbexiv** [tobbexiv/pagekit-widget-includer#2]
An icon for the widget button in the editor needs to be selected.

Suggestions:
- uk-icon-puzzle-piece
  ![uk-icon-puzzle-piece](https://cloud.githubusercontent.com/assets/5681598/17229648/efa1c6ca-5518-11e6-8164-6742291fdbad.png)
- uk-icon-gears
  ![uk-icon-gears](https://cloud.githubusercontent.com/assets/5681598/17229670/026a0498-5519-11e6-8137-0d19da194fb0.png)
- uk-icon-gear
  ![uk-icon-gear](https://cloud.githubusercontent.com/assets/5681598/17229667/fb10388e-5518-11e6-82db-7243f6af1bd7.png)

---

I would suggest the gears, but puzzle piece would also be possible. I would not use gear as this is to similar to "options".

@jdegger suggested puzzle piece. Maybe you can check again what you think suits best if you see it in place?

Any other suggestions? Is there any opinion from you @pagekit as the widgets are a feature of pagekit which is only extended by me?

**Comment by jdegger** [comment]
paging @MalteScharenberg

As for my opinion I really think the puzzle piece is fine. It suggests you're injecting something as where by the cogs I'm feeling like you're doing something in the editor settings.

**Comment by tobbexiv** [comment]
As there was no reaction till now, I will go with the puzzle piece for now. Might be changed until release if there is an reaction. Thus keeping the issue open if there are other opinions.

**Comment by tobbexiv** [comment]
I will stick to the puzzle as there were no other comments till now and a change in the icon migth confuse the users of the extension.
