### ISSUE TITLE
Widget title instead of just "widget" in editor

### ISSUE THREAD

**Issue by benedictdudel** [tobbexiv/pagekit-widget-includer#6]
Hey,

first of all thank you for this PageKit extension. It makes working with widgets very easy for the end-user.

But I think it would be awesome if the user can better distinguish in the editor which widgets he is gonna include. If he just sees `(widget){...}` he can't distinguish the widgets.

As a workaround, we need to give the widget a title and then have to tick the "hide title option".

I would like to see that the plugin doesn't hide the title in the modal on ticking the hide title option **or** that `(widget){..}` would be replaced by the widget title.

Keep up the good work!

**Comment by tobbexiv** [comment]
Hi benedu,

thanks for your feedback. I also thought about this problem and found different possible solutions for it.
1. Introduce a new field for description / comment. This field will be always shown in the modal and in the editor, but not evaluated by the includer. So you can enter freely any text you want.
2. Do not hide the title if you tick "hide title". This means that you can enter and see the title in the modal even if you do not want to use it. The disavantage I see is that if you want to use the title you can not enter additional information. Or if you want to use the default title you should not enter anything in this field. So it can not be used in every situation.
3. You can see the default title in the Modal. So copying it to a field which is invisible in the modal, but visible in the editor ensures that you can always see the title. Disadvantage is that you can not customize it.

What will not work is your second suggestion. `(pluginname){...}` is a generic template in Pagekit for editor plugins. So changing it from edito to something else will break the recognition of the plugin.

So I tend to implement solution (1) which means that you have a comment field in the modal and editor which has no influence on the plugin itself. What is your opinion on these suggestions? Or do you have improvements to one of them?
