### ISSUE TITLE
custom dev

### ISSUE THREAD

**Issue by Cryptoneur** [tobbexiv/pagekit-widget-includer#7]
Tobbexiv - 

I am looking to have some custom pagekit development work done.

Pls contact me directly jonathan ((at)) fitrepreneur ((dot)) me.

JM

**Comment by tobbexiv** [comment]
Closing as this is not related to this extension as far as I see. Please specify more specifically what is your suggestion / issue if it is related.

If you have another issue you can contact me by responding to the mail I sent you.
